title: My Blog
description: Chenrun Wang's blog about life and technology.
url: "https://wcr369.github.io"
baseurl: ""

theme: jekyll-theme-minimal

author: Chenrun Wang
# avatar: "https://avatars.githubusercontent.com/u/123456?v=4"
email: 1282713208@qq.com
social:
  github: wcr369
  google_scholar: "https://scholar.google.com/citations?user=bTBkHegAAAAJ"
  # twitter: username
  # linkedin: username

menu:
  - name: Home
    url: "https://wcr369.github.io"
  - name: xiaohongshu
    url: "https://www.xiaohongshu.com/user/profile/6104a7de0000000001002868"
  - name: Blog
    url: /blog
  - name: Contact
    url: /contact

# paginate: 5
# paginate_path: "/blog/page:num/"

# comments:
#   provider: disqus
#   disqus:
#     shortname: myblog-disqus-shortname

timezone: Asia/Shanghai
markdown: kramdown
highlighter: rouge
