title: My Blog
description: Chenrun Wang's blog about life and technology.
url: "https://wcr369.github.io"
baseurl: ""

theme: jekyll-theme-minimal

author: Chenrun Wang

social:
  github: wcr369


menu:
  - name: Home
    url: "https://wcr369.github.io"

markdown: kramdown
highlighter: rouge
